name: CFN Church
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48963
title: CFN Church
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#1c95b0'
    - '#484848'
    - '#030708'
    - '#cdba90'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
