name: CFN Church
favicon: null
layout_spectrum: 0.17111679795198143
typography_spectrum: 0.17228871234692633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3814637472387403
  lightness: 0.6714531839825213
  saturation: 0.3079427173361182
  rhythmicContrast: 0.3000490218400955
purpose: []
